LOG_APP_VAR_ENV = "Environment:"
LOG_APP_VAR_QUERY = "Query parameters:"
LOG_APP_STEP_SEND = "Sending message..."
LOG_APP_STEP_RESPONSE = "Response"

LOG_PARAM_ERR_NOT_DEFINED = "<not defined>"
LOG_PARAM_ERR_EMPTY = "<empty>"
LOG_PARAM_ERR_NOT_FOUND = "<not found>"
LOG_PARAM_ERR_WRONG = "Not all params are specified or specified bot and users should be defined in config, also text should not be blank. No sending performed."
LOG_PARAM_ERR_RIGHTS = "All specified users have no access to the specified bot. No sending performed."
LOG_PARAM_ERR_RIGHTS_SOME = "Some specified users have no access to the specified bot, they are skipped"
